#Aerospike property
spring:
  aerospike:
    hostname: 192.168.105.145
    port: 3000
    namespace: test
    
logging:
  level:
    netgloo: DEBUG
    root: WARN
    org.springframework: ERROR
    org.hibernate: ERROR
    com.aerospike: DEBUG
